#!/usr/bin/env bash

cwd="$(cd "$(dirname "$0")" && pwd)"
dir=$(mktemp -d -t fly-build-boclips-js-security.XXXXX)

tidy () {
    rm -rf "$dir"
}

trap tidy EXIT

fly --target ci execute \
    --input source="$cwd" \
    --config "$cwd/pipeline/test.yml" \
    --output dist=fly-dist
