#!/usr/bin/env bash

npm run demo &
demo_webserver_pid=$!

CYPRESS_TEACHERS_USERNAME="$(lpass show e2e-teachers-testing --username)"
CYPRESS_TEACHERS_PASSWORD="$(lpass show e2e-teachers-testing --password)"

cleanup() {
        echo "Killing webserver with pid: $demo_webserver_pid"
        kill "$demo_webserver_pid"
}

trap "cleanup" INT QUIT TERM EXIT
npm run e2e:ci