#!/usr/bin/env bash

set -e

CYPRESS_USERNAME="$(bo show credential concourse-main boclips-js-security.test username)"
export CYPRESS_USERNAME
CYPRESS_PASSWORD="$(bo show credential concourse-main boclips-js-security.test password)"
export CYPRESS_PASSWORD

git pull -r

npm i
npm run audit
npm run compile
npm run build
npm run test

./run_e2e

git push
