#!/usr/bin/env bash

set -e

export CYPRESS_USERNAME="$(get-k8s-concourse-secret boclips-js-security test username)"
export CYPRESS_PASSWORD="$(get-k8s-concourse-secret boclips-js-security test password)"

git pull -r

npm i
npm run audit-ci
npm run compile
npm run build
npm run test

./run_e2e

git push
