#!/usr/bin/env bash

set -eu

cwd="$(cd "$(dirname $0)" && pwd)"

fly --target ci \
    set-pipeline \
    --pipeline boclips-js-security \
    --config $cwd/pipeline.yml \
    --var boclips-js-security-repo-key="$(lpass show concourse-boclips-js-security-repo-key --notes)" \
    --var versions-repo-key="$(lpass show concourse-versions-repo-key --notes)" \
    --var npm-username="$(lpass show npmjs --username)" \
    --var npm-password="$(lpass show npmjs --password)" \
